insert into books(id, author, title, imageURL, price, description,  rating) values (1,'Chetan Bhagat', 'The Girl in Room 105', 'http://books.google.com/books/content?id=GHt_uwEACAAJ&printsec=frontcover&img=1&zoom=5',193,'Hi, I''m Keshav, and my life is screwed. I hate my job and my girlfriend left me. Ah, the beautiful Zara. Zara is from Kashmir. She is a Muslim. And did I tell you my family is a bit, well, traditional? Anyway, leave that. Zara and I broke up four years ago. She moved on in life. I didn''t. I drank every night to forget her. I called, messaged, and stalked her on social media. She just ignored me. However, that night, on the eve of her birthday, Zara messaged me. She called me over, like old times, to her hostel room 105. I shouldn''t have gone, but I did... and my life changed forever. This is not a love story. It is an unlove story.From the author of Five Point Someone and 2 States, comes a fast-paced, funny and unputdownable thriller about obsessive love and finding purpose in life against the backdrop of contemporary India.', 2);

insert into books(id, author, title, imageURL, price, description,  rating) values (2,'Rujuta Divekar', 'Indian Superfoods', 'http://books.google.com/books/content?id=4oFoDwAAQBAJ&printsec=frontcover&img=1&zoom=5',495,  'Forget about acacia seeds and goji berries. The secret foods for health, vitality and weight loss lie in our own kitchens and backyards. Top nutritionist Rujuta Diwekar talks you through the ten Indian superfoods that will completely transform you',5);

insert into books(id, author, title, imageURL, price, description,  rating) values (3,'Dan Brown', 'Angels And Demons', 'http://books.google.com/books/content?id=d5xgYw4Ts0gC&printsec=frontcover&img=1&zoom=5',218,  '*INCLUDES A SNEAK PREVIEW OF ORIGIN,THE NEW THRILLER BY DAN BROWN: OUT 3RD OCTOBER. PRE-ORDER TODAY* --------------------------------------------------------------------------------------------------- CERN Institute, Switzerland: a world-renowned scientist is found brutally murdered with a mysterious symbol seared onto his chest. The Vatican, Rome: the College of Cardinals assembles to elect a new pope. Somewhere beneath them, an unstoppable bomb of terrifying power relentlessly counts down to oblivion. In a breathtaking race against time, Harvard professor Robert Langdon must decipher a labyrinthine trail of ancient symbols if he is to defeat those responsible - the Illuminati, a secret brotherhood presumed extinct for nearly four hundred years, reborn to continue their deadly vendetta against their most hated enemy, the Catholic Church.',4);

insert into books(id, author, title, imageURL, price, description,  rating) values (4,'Dan Brown', 'Angels & Demons - Movie Tie-In', 'http://books.google.com/books/content?id=GXznEnKwTdAC&printsec=frontcover&img=1&zoom=5',462, 'The murder of a world-famous physicist raises fear that the Illuminati are operating again after centuries of silence, and religion professor Robert Langdon is called in to assist with the case. By the author of Digital Fortress. Reprint.', 5);

insert into books(id, author, title, imageURL, price, description,  rating) values (5,'Dan Brown', 'Origin', 'http://books.google.com/books/content?id=95wnDQAAQBAJ&printsec=frontcover&img=1&zoom=5',174, 'Sunday Times #1 Bestseller New York Times #1 Bestseller The global bestseller - Origin is the latest Robert Langdon novel from the author of The Da Vinci Code. Fans will not be disappointed The Times Robert Langdon, Harvard professor of symbology and religious iconology, arrives at the Guggenheim Museum Bilbao to attend the unveiling of an astonishing scientific breakthrough. The evening’s host is billionaire Edmond Kirsch, a futurist whose dazzling high-tech inventions and audacious predictions have made him a controversial figure around the world. But Langdon and several hundred guests are left reeling when the meticulously orchestrated evening is suddenly blown apart. There is a real danger that Kirsch’s precious discovery may be lost in the ensuing chaos. With his life under threat, Langdon is forced into a desperate bid to escape Bilbao, taking with him the museum’s director, Ambra Vidal. Together they flee to Barcelona on a perilous quest to locate a cryptic password that will unlock Kirsch’s secret. To evade a devious enemy who is one step ahead of them at every turn, Langdon and Vidal must navigate the labyrinthine passageways of extreme religion and hidden history. On a trail marked only by enigmatic symbols and elusive modern art, Langdon and Vidal will come face-to-face with a breathtaking truth that has remained buried – until now. ‘Dan Brown is the master of the intellectual cliffhanger’ Wall Street Journal ‘As engaging a hero as you could wish for’ Mail on Sunday ‘For anyone who wants more brain-food than thrillers normally provide’ Sunday Times',4);

insert into books(id, author, title, imageURL, price, description,  rating) values (6,'Dan Brown', 'Deception Point', 'http://books.google.com/books/content?id=tYwq0H5HcrcC&printsec=frontcover&img=1&zoom=5',128, '*INCLUDES A SNEAK PREVIEW OF ORIGIN,THE NEW THRILLER BY DAN BROWN: OUT 3RD OCTOBER. PRE-ORDER TODAY* --------------------------------------------------------------------------------------------------- When a new NASA satellite detects evidence of an astonishingly rare object buried deep in the Arctic ice, the floundering space agency proclaims a much-needed victory...a victory that has profound implications for U.S. space policy and the impending presidential election. With the Oval Office in the balance, the President dispatches White House Intelligence analyst Rachel Sexton to the Arctic to verify the authenticity of the find. Accompanied by a team of experts, including the charismatic academic Michael Tolland, Rachel uncovers the unthinkable - evidence of scientific trickery - a bold deception that threatens to plunge the world into controversy...',3);

insert into books(id, author, title, imageURL, price, description,  rating) values (7,'Dan Brown', 'Digital Fortress', 'http://books.google.com/books/content?id=pfB9VsrdX4IC&printsec=frontcover&img=1&zoom=5',573, '*INCLUDES A SNEAK PREVIEW OF ORIGIN,THE NEW THRILLER BY DAN BROWN: OUT 3RD OCTOBER. PRE-ORDER TODAY* --------------------------------------------------------------------------------------------------- When the National Security Agencys invincible code-breaking machine encounters a mysterious code it cannot break, the agency calls in its head cryptographer, Susan Fletcher, a brilliant, beautiful mathematician. What she uncovers sends shock waves through the corridors of power. The NSA is being held hostage - not by guns or bombs, but by a code so complex that if released would cripple U.S. intelligence. Caught in an accelerating tempest of secrecy and lies, Fletcher battles to save the agency she believes in. Betrayed on all sides, she finds herself fighting not only for her country but for her life, and in the end, for the life of the man she loves...' , 3);

insert into books(id, author, title, imageURL, price, description,  rating) values (8,'Dan Brown', 'Inferno', 'http://books.google.com/books/content?id=9nloexmq6QsC&printsec=frontcover&img=1&zoom=5',951, '#1 WORLDWIDE BESTSELLER Harvard professor of symbology Robert Langdon awakens in an Italian hospital, disoriented and with no recollection of the past thirty-six hours, including the origin of the macabre object hidden in his belongings. With a relentless female assassin trailing them through Florence, he and his resourceful doctor, Sienna Brooks, are forced to flee. Embarking on a harrowing journey, they must unravel a series of codes, which are the work of a brilliant scientist whose obsession with the end of the world is matched only by his passion for one of the most influential masterpieces ever written, Dante Alighieris The Inferno. Dan Brown has raised the bar yet again, combining classical Italian art, history, and literature with cutting-edge science in this captivating thriller.' , 2);

insert into books(id, author, title, imageURL, price, description,  rating) values (9,'Dan Brown', 'The Da Vinci Code', 'http://books.google.com/books/content?id=ivzfRJGrdFsC&printsec=frontcover&img=1&zoom=5',348, '*INCLUDES AN EXTRACT FROM ORIGIN,THE NEW THRILLER BY DAN BROWN: OUT NOW* --------------------------------------------------------------------------------------------------- Harvard professor Robert Langdon receives an urgent late-night phone call while on business in Paris: the elderly curator of the Louvre has been brutally murdered inside the museum. Alongside the body, police have found a series of baffling codes. As Langdon and a gifted French cryptologist, Sophie Neveu, begin to sort through the bizarre riddles, they are stunned to find a trail that leads to the works of Leonardo Da Vinci - and suggests the answer to a mystery that stretches deep into the vault of history. Unless Langdon and Neveu can decipher the labyrinthine code and quickly assemble the pieces of the puzzle, a stunning historical truth will be lost forever...' , 5);

insert into books(id, author, title, imageURL, price, description,  rating) values (10,'Dan Brown', 'Robert Langdon Omnibus', 'http://books.google.com/books/content?id=IqPW7mqq6GIC&printsec=frontcover&img=1&zoom=5',451, 'Thriller. Two books in one.' ,1);

insert into books(id, author, title, imageURL, price, description,  rating) values (11,'Dan Brown', 'Angels And Demons', 'http://books.google.com/books/content?id=d5xgYw4Ts0gC&printsec=frontcover&img=1&zoom=5',612, '*INCLUDES A SNEAK PREVIEW OF ORIGIN,THE NEW THRILLER BY DAN BROWN: OUT 3RD OCTOBER. PRE-ORDER TODAY* --------------------------------------------------------------------------------------------------- CERN Institute, Switzerland: a world-renowned scientist is found brutally murdered with a mysterious symbol seared onto his chest. The Vatican, Rome: the College of Cardinals assembles to elect a new pope. Somewhere beneath them, an unstoppable bomb of terrifying power relentlessly counts down to oblivion. In a breathtaking race against time, Harvard professor Robert Langdon must decipher a labyrinthine trail of ancient symbols if he is to defeat those responsible - the Illuminati, a secret brotherhood presumed extinct for nearly four hundred years, reborn to continue their deadly vendetta against their most hated enemy, the Catholic Church.' , 3);

insert into books(id, author, title, imageURL, price, description,  rating) values (12,'Dan Brown', 'Origin – Read a Free Sample Now', 'http://books.google.com/books/content?id=Wj81DwAAQBAJ&printsec=frontcover&img=1&zoom=5',530, 'An extract from Origin, the spell-binding new thriller from the bestselling author of The Da Vinci Code and Inferno. Dan Brown’s new novel, Origin, features renowned Harvard symbologist Robert Langdon and is set in Spain, where Langdon is drawn into a terrifying race against time that will bring him face-to-face with a world-shaking truth that has remained buried – until now. This preview includes the prologue and first chapter of Origin. Origin is out on 3rd October 2017. ‘Dan Brown is the master of the intellectual cliffhanger’ Wall Street Journal ‘As engaging a hero as you could wish for’ Mail on Sunday ‘For anyone who wants more brain-food than thrillers normally provide’ Sunday Times' , 4);

insert into books(id, author, title, imageURL, price, description,  rating) values (13,'Dan Brown', 'Inferno - Illustrated Edition', 'http://books.google.com/books/content?id=IPsKBAAAQBAJ&printsec=frontcover&img=1&zoom=5',415, 'SEEK AND YOU WILL FIND Florence: Harvard symbologist Robert Langdon awakes in a hospital bed with no recollection of where he is or how he got there. Nor can he explain the origin of the macabre object that is found hidden in his belongings. A threat to his life will propel him and a young doctor, Sienna Brooks, into a breakneck chase across the city. Only Langdon’s knowledge of the hidden passageways and ancient secrets that lie behind its historic facade can save them from the clutches of their unknown pursuers. With only a few lines from Dante’s The Inferno to guide them, they must decipher a sequence of codes buried deep within some of the Renaissance’s most celebrated artworks to find the answers to a puzzle which may, or may not, help them save the world from a terrifying threat... When it was published in the summer of 2013, Inferno became a global sensation, selling over 15 million copies in hardcover. This new and exclusive illustrated edition illuminates the sights and cities which form the backdrop to Dan Brown’s most thought-provoking and compelling novel yet, and reveals the rich tapestry of history, art and literature which inspired its narrative.' ,3);

